version: "3.7"

services:
  example:
    container_name: shawandpartners-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/backend"
      - "/backend/node_modules"
    ports:
      - "3000:3000"
